modLoader="javafml" #M
loaderVersion="[40,)" #M
license="GNU GPL v3, https://www.gnu.org/licenses/gpl-3.0.en.html" #M
#issueTrackerURL="https://github.com/Hxrlio/EnderDream/issues" #O

[[mods]] #M
modId="enderdream" #M
version="${file.jarVersion}" #M
displayName="Ender Dream" #M
#updateJSONURL="NONE" #O
displayURL="https://modrinth.com/project/ender-dream" #O
logoFile="EnderDream.png" #O
#credits="" #O
authors="Hxrl" #O

# MATCH_VERSION = BOTH
# IGNORE_SERVER_VERSION = SERVER
# IGNORE_ALL_VERSION = CLIENT
# NONE = OTHER IExtensionPoint.DisplayTest for more
displayTest="MATCH_VERSION" # MATCH_VERSION is default (#O)

description='''
The Ender Dragon rules over the domain of dreams... how else would she amass so many victims?
''' #M

[[dependencies.customcoords]]
    modId="forge" #M
    mandatory=true #M
    versionRange="[40,)" #M
    # BEFORE / AFTER / NONE
    ordering="AFTER" #M
    # BOTH / CLIENT / SERVER
    side="BOTH" #M

[[dependencies.customcoords]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="AFTER"
    side="BOTH"